project:
  type: website

  output-dir: docs
  preview:
    port: 4200

website:
  title: "After iNaturalist"
  sidebar:
    style: "docked"
    contents:
      - text: "Home"
        href: index.qmd
      - lessons/setup.qmd
      - lessons/intro-data-analysis.qmd
      - lessons/intro-science-coding.qmd
      - lessons/intro-r-rstudio.qmd
      - lessons/working-with-data.qmd
      - lessons/understanding-data.qmd
      - lessons/creating-maps.qmd
      - lessons/creating-charts.qmd
      - lessons/other-datasets.qmd
      - lessons/next-steps.qmd
      - section: "Extra"
        contents:
          - lessons/additional-analysis.qmd
          - lessons/editing-geo-files.qmd
          - lessons/cleaning-data.qmd
          - lessons/setup-local.qmd


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual


